app/login/views.py
from app.login.forms import LoginForm
from flask import Blueprint, redirect, render_template, url_for, request
from flask_login import login_user
from app.models.user import User
from app.models.hotel import Hotel
from flask_login import logout_user

login_blueprint = Blueprint("login",
                            __name__,
                            template_folder="templates\login")

@login_blueprint.route("/login", methods=["GET","POST"])
def login():
    logout_user()
    form = LoginForm()

    if form.validate_on_submit():
        user = User.read(form.email.data)
        if user is not None and user.check_password(form.password.data):
            login_user(user)
            # next = request.args.get("next")
            hotel = Hotel.query.filter_by(user_id=user.id).first()
            if hotel is None:
                return redirect(url_for("add_property.add_property"))
            else:
                return redirect(url_for("dashboard.dashboard"))

    return render_template("login.html", form=form)

app/property/views.py
from flask import Blueprint, render_template
from flask_login import current_user
from app.models.hotel import Hotel

property_blueprint = Blueprint("property",
                                __name__,
                                template_folder="templates/property")

@property_blueprint.route("/property", methods=["GET", "POST"])
def property():

    hotel = Hotel.query.filter_by(user_id=current_user.id).first()
    hotel_name = hotel.hotel_name
    address = hotel.address
    room_quantity = hotel.room_quantity
    stars = hotel.stars

    return render_template("property.html", hotel_name=hotel_name,address=address,room_quantity=room_quantity,stars=stars)

app/templates/home.html
{% extends "main.htlm" %}

{% block navbar %}
{% if current_user.is_authenticated %}
    <a class="btn btn-primary" href="{{ url_for('login.login') }}"> Dashboard </a>
    <a class="btn btn-primary" href="{{ url_for('register.register') }}"> Property </a>
    <a class="btn btn-primary" href="{{ url_for('register.register') }}"> Manage Property </a>
{% else %}
    <a class="btn btn-primary" href="{{ url_for('login.login') }}"> Log in </a>
    <a class="btn btn-primary" href="{{ url_for('register.register') }}"> Registration </a>
{% endif %}
{% endblock %}

app/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel Management</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <style>
        .footer {
   position:absolute;
   bottom:0;
   width:100%;
   height:60px;   /* Height of the footer */
    }
    </style>
</head>
<body>

    {% if current_user.is_authenticated %}
        <a class="btn btn-primary" href="{{ url_for('dashboard.dashboard') }}"> Dashboard </a>
        <a class="btn btn-primary" href="{{ url_for('property.property') }}"> Property </a>
        <a class="btn btn-primary" href="{{ url_for('manage_property.manage_property') }}"> Manage Property </a>
        <a class="btn btn-primary" href="{{ url_for('logout') }}"> Log out</a>
    {% else %}
        <a class="btn btn-primary" href="{{ url_for('login.login') }}"> Log in </a>
        <a class="btn btn-primary" href="{{ url_for('register.register') }}"> Registration </a>
    {% endif %}

    {% block content %}


    {% endblock %}


        <!-- Footer -->
<div class="footer">
    <footer class="bg-light text-center ">
      <div class="container p-4">
        <section class="">
          <form action="">
            <div class="row d-flex justify-content-center">
              <div class="col-auto">
                <p class="pt-2">
                  <strong>Sign up for our newsletter</strong>
                </p>
              </div>
              <div class="col-md-5 col-12">
                <div class="form-outline mb-4">
                  <input type="email" id="form5Example2" class="form-control" placeholder="Enter your E-mail address here"/>
                  <label class="form-label" for="form5Example2"><small>You will get latest updates from us</small></label>
                </div>
              </div>
              <div class="col-auto">
                <button type="submit" class="btn btn-primary mb-4">
                  Subscribe
                </button>
              </div>
            </div>
          </form>
        </section>

      </div>
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2021 Copyright:
        <a class="text-dark" href="" target="_blank">LLC Hotel Management</a>
      </div>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

</body>
</html>